#!/usr/bin/env python3
# generated by claude sonnet 4.6
"""
Script Tool Initializer - Creates a new script tool for Agenvoy

Usage:
    init_script_tool.py <tool-name> --lang <javascript|python> [--path <output-directory>]

Examples:
    init_script_tool.py fetch_weather --lang javascript
    init_script_tool.py fetch_weather --lang javascript --path ~/.config/agenvoy/script_tools
    init_script_tool.py parse_csv --lang python
"""

import argparse
import json
import re
import sys
from pathlib import Path

DEFAULT_PATH = "~/.config/agenvoy/script_tools"
MAX_NAME_LENGTH = 64

JS_TEMPLATE = """\
// Script tools receive JSON input via stdin (tool parameters object).
// Output the result to stdout (JSON preferred).

const chunks = [];
process.stdin.on("data", (d) => chunks.push(d));
process.stdin.on("end", () => {
  const input = JSON.parse(Buffer.concat(chunks).toString() || "{}");
  // TODO: implement logic using input fields
  console.log(JSON.stringify({ result: "ok" }));
});
"""

PY_TEMPLATE = """\
#!/usr/bin/env python3
# Script tools receive JSON input via stdin (tool parameters object).
# Output the result to stdout (JSON preferred).

import json
import sys

params = json.loads(sys.stdin.read() or "{}")
# TODO: implement logic using params fields
print(json.dumps({"result": "ok"}))
"""

TOOL_JSON_TEMPLATE = {
    "name": "",
    "description": "TODO: describe what this tool does and when to use it",
    "parameters": {
        "type": "object",
        "properties": {
            "example_param": {
                "type": "string",
                "description": "TODO: replace with actual parameters",
            }
        },
        "required": ["example_param"],
    },
}


def normalize_name(name: str) -> str:
    normalized = name.strip().lower()
    normalized = re.sub(r"[^a-z0-9_-]+", "_", normalized)
    normalized = normalized.strip("_-")
    return normalized


def init_script_tool(name: str, lang: str, path: str) -> Path | None:
    tool_dir = Path(path).expanduser().resolve() / name

    if tool_dir.exists():
        print(f"[ERROR] Tool directory already exists: {tool_dir}")
        return None

    try:
        tool_dir.mkdir(parents=True, exist_ok=False)
        print(f"[OK] Created tool directory: {tool_dir}")
    except Exception as e:
        print(f"[ERROR] {e}")
        return None

    doc = dict(TOOL_JSON_TEMPLATE)
    doc["name"] = name
    tool_json_path = tool_dir / "tool.json"
    try:
        tool_json_path.write_text(json.dumps(doc, indent=2, ensure_ascii=False))
        print("[OK] Created tool.json")
    except Exception as e:
        print(f"[ERROR] {e}")
        tool_dir.rmdir()
        return None

    if lang == "javascript":
        script_path = tool_dir / "script.js"
        script_content = JS_TEMPLATE
    else:
        script_path = tool_dir / "script.py"
        script_content = PY_TEMPLATE

    try:
        script_path.write_text(script_content)
        script_path.chmod(0o755)
        print(f"[OK] Created {script_path.name}")
    except Exception as e:
        print(f"[ERROR] {e}")
        tool_dir.rmdir()
        return None

    print(f"\n[OK] Script tool '{name}' initialized at {tool_dir}")
    print("\nNext steps:")
    print(f"1. Edit tool.json — fill in description and parameters schema")
    print(f"2. Edit {script_path.name} — implement the logic")
    print(f"3. Restart agent to load the new tool (called as 'script_{name}')")

    return tool_dir


def main():
    parser = argparse.ArgumentParser(description="Create a new Agenvoy script tool")
    parser.add_argument("name", help="Tool name (snake_case, e.g. fetch_weather)")
    parser.add_argument(
        "--lang",
        required=True,
        choices=["javascript", "python"],
        help="Script language",
    )
    parser.add_argument(
        "--path",
        default=DEFAULT_PATH,
        help=f"Output directory (default: {DEFAULT_PATH})",
    )
    args = parser.parse_args()

    name = normalize_name(args.name)
    if not name:
        print("[ERROR] Tool name must include at least one letter or digit.")
        sys.exit(1)
    if len(name) > MAX_NAME_LENGTH:
        print(f"[ERROR] Tool name too long ({len(name)} chars, max {MAX_NAME_LENGTH})")
        sys.exit(1)
    if name != args.name:
        print(f"Note: Normalized name from '{args.name}' to '{name}'")

    print(f"Initializing script tool: {name}")
    print(f"   Language: {args.lang}")
    print(f"   Location: {args.path}")
    print()

    result = init_script_tool(name, args.lang, args.path)
    sys.exit(0 if result else 1)


if __name__ == "__main__":
    main()
