#!/usr/bin/env bash
# generated by claude sonnet 4.6
set -euo pipefail

# ─────────────────────────────────────────────
#  yt-dlp one-time installation & setup
# ─────────────────────────────────────────────
INSTALL_DIR="$HOME/.config/agenvoy/script_tools"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)/extensions/scripts"
OS="$(uname -s)"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
ok()   { echo -e "  ${GREEN}✓${NC} $*"; }
warn() { echo -e "  ${YELLOW}!${NC} $*"; }
err()  { echo -e "  ${RED}✗${NC} $*"; exit 1; }

install_ffmpeg() {
    if [ "$OS" = "Darwin" ]; then
        command -v brew &>/dev/null || err "找不到 Homebrew，請先安裝：https://brew.sh"
        brew install ffmpeg --quiet
    elif command -v apt-get &>/dev/null; then
        sudo apt-get install -y ffmpeg
    elif command -v dnf &>/dev/null; then
        sudo dnf install -y ffmpeg
    elif command -v pacman &>/dev/null; then
        sudo pacman -S --noconfirm ffmpeg
    else
        err "無法自動安裝 ffmpeg，請手動安裝：https://ffmpeg.org/download.html"
    fi
}

# ── Step 1: Install yt-dlp (binary, no pip) ──────────────────────────────────
echo ""
echo "  ┌─ Step 1: 安裝 yt-dlp"
if command -v yt-dlp &>/dev/null; then
    ok "yt-dlp 已安裝（$(yt-dlp --version)）"
else
    warn "yt-dlp 未安裝，下載 binary..."
    if [ "$OS" = "Darwin" ]; then
        command -v brew &>/dev/null || err "找不到 Homebrew，請先安裝：https://brew.sh"
        brew install yt-dlp --quiet
    else
        # Linux: install binary to ~/.local/bin to avoid sudo
        mkdir -p "$HOME/.local/bin"
        curl -fsSL "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp" \
            -o "$HOME/.local/bin/yt-dlp"
        chmod +x "$HOME/.local/bin/yt-dlp"
        # Warn if ~/.local/bin is not in PATH
        case ":$PATH:" in
            *":$HOME/.local/bin:"*) ;;
            *) warn "請將 \$HOME/.local/bin 加入 PATH（在 ~/.bashrc 或 ~/.zshrc 加入：export PATH=\"\$HOME/.local/bin:\$PATH\"）" ;;
        esac
    fi
    ok "yt-dlp 安裝完成（$(yt-dlp --version 2>/dev/null || echo 'installed')）"
fi

# ── Step 2: Install ffmpeg ───────────────────────────────────────────────────
echo ""
echo "  ┌─ Step 2: 檢查 ffmpeg（影音合併所需）"
if command -v ffmpeg &>/dev/null; then
    ok "ffmpeg 已安裝（$(ffmpeg -version 2>&1 | head -1 | awk '{print $3}')）"
else
    warn "ffmpeg 未安裝，安裝中..."
    install_ffmpeg && ok "ffmpeg 安裝完成"
fi

# ── Step 3: Install script tools ────────────────────────────────────────────
echo ""
echo "  ┌─ Step 3: 安裝 yt-dlp 工具到 $INSTALL_DIR"
mkdir -p "$INSTALL_DIR"
count=0
for dir in "$SCRIPT_DIR"/yt-dlp*/; do
    [ -d "$dir" ] || continue
    name=$(basename "$dir")
    cp -r "$dir" "$INSTALL_DIR/$name"
    ok "$name"
    count=$((count + 1))
done
[ "$count" -gt 0 ] || err "找不到 extensions/scripts/yt-dlp* 目錄，請確認從專案根目錄執行此腳本"

# ── Done ─────────────────────────────────────────────────────────────────────
echo ""
echo "  ════════════════════════════════════════"
ok "yt-dlp 工具安裝完成！"
echo ""
echo "     已安裝工具："
echo "       • yt-dlp-info       — 查詢影片 metadata 與格式清單"
echo "       • yt-dlp-downloader — 下載影片或音訊"
echo ""
warn "下載 1080p 以上需搭配 ffmpeg 合併影音串流"
echo "  ════════════════════════════════════════"
echo ""
