#!/usr/bin/env bash
# generated by claude sonnet 4.6
set -euo pipefail

# ─────────────────────────────────────────────
#  Threads API one-time installation & setup
# ─────────────────────────────────────────────
GRAPH="https://graph.threads.net"
SERVICE="agenvoy.threads"
INSTALL_DIR="$HOME/.config/agenvoy/script_tools"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)/extensions/scripts"
OS="$(uname -s)"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
ok()   { echo -e "  ${GREEN}✓${NC} $*"; }
warn() { echo -e "  ${YELLOW}!${NC} $*"; }
err()  { echo -e "  ${RED}✗${NC} $*"; exit 1; }

AGENVOY_API="http://localhost:17989"

# ── Preflight: check Agenvoy is running ─────────────────────────────────────
echo ""
echo "  ┌─ 檢查 Agenvoy 服務 (port 17989)..."
# curl without -f: exits 0 on any HTTP response (including 4xx), non-zero only on connection failure
if curl -s --connect-timeout 3 --max-time 3 "${AGENVOY_API}/v1/key?key=__ping__" -o /dev/null 2>&1; then
    ok "Agenvoy 已啟動"
else
    err "Agenvoy 尚未啟動，請先執行：go run ./cmd/app"
fi

urlencode() {
    python3 -c "import urllib.parse, sys; print(urllib.parse.quote(sys.argv[1]))" "$1"
}

json_get() {
    # json_get <json_string> <key>
    echo "$1" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('$2',''))"
}

json_nested_get() {
    # json_nested_get <json_string> <key1> <key2>
    echo "$1" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('$2',{}).get('$3',''))"
}

# ── Step 1: Install script tools ────────────────────────────────────────────
echo ""
echo "  ┌─ Step 1: 安裝 Threads 工具到 $INSTALL_DIR"
mkdir -p "$INSTALL_DIR"
count=0
for dir in "$SCRIPT_DIR"/threads*/; do
    [ -d "$dir" ] || continue
    name=$(basename "$dir")
    cp -r "$dir" "$INSTALL_DIR/$name"
    ok "$name"
    count=$((count + 1))
done
[ "$count" -gt 0 ] || err "找不到 extensions/scripts/threads* 目錄，請確認從專案根目錄執行此腳本"

# ── Step 2: Collect app credentials ─────────────────────────────────────────
echo ""
echo "  ┌─ Step 2: Threads 設定"
echo "  │  請至 https://developers.facebook.com/apps 準備以下資訊："
echo "  │  App ID 與 App Secret 可在應用程式設定頁面找到"
echo "  │  Short-lived token 請至 Graph API Explorer 產生："
echo "  │  https://developers.facebook.com/tools/explorer"
echo "  │"
read -rp "  │  App ID: " APP_ID
read -rsp "  │  App Secret: " APP_SECRET
echo ""
read -rsp "  │  Short-lived Token (from Graph API Explorer): " SHORT_TOKEN
echo ""

# ── Request 1: short-lived → long-lived token ────────────────────────────────
echo ""
echo "  ┌─ [1/2] 換取 Long-Lived Token..."
R2=$(curl -sf "${GRAPH}/access_token?grant_type=th_exchange_token&client_id=$(urlencode "$APP_ID")&client_secret=$(urlencode "$APP_SECRET")&access_token=$(urlencode "$SHORT_TOKEN")") \
    || err "請求失敗"

LONG_TOKEN=$(json_get "$R2" "access_token")
EXPIRES_IN=$(json_get "$R2" "expires_in")
[ -n "$LONG_TOKEN" ] || err "$(json_nested_get "$R2" "error" "message")"
DAYS=$(( EXPIRES_IN / 86400 ))
ok "Long-lived token 取得成功（有效約 ${DAYS} 天）"

# ── Request 2: get user_id ───────────────────────────────────────────────────
echo ""
echo "  ┌─ [2/2] 取得 User ID..."
R3=$(curl -sf "${GRAPH}/me?access_token=$(urlencode "$LONG_TOKEN")") || err "請求失敗"

USER_ID=$(json_get "$R3" "id")
USERNAME=$(json_get "$R3" "username")
[ -n "$USER_ID" ] || err "無法取得 User ID：$R3"
ok "User ID: ${USER_ID}$( [ -n "$USERNAME" ] && echo " (@${USERNAME})" || true )"

# ── Save credentials via Agenvoy API ────────────────────────────────────────
echo ""
echo "  ┌─ 儲存憑證至 Agenvoy ($AGENVOY_API)..."
store_key() {
    local key="$1" value="$2"
    local payload resp
    payload=$(python3 -c "import json,sys; print(json.dumps({'key':sys.argv[1],'value':sys.argv[2]}))" "$key" "$value")
    resp=$(curl -sf -X POST "${AGENVOY_API}/v1/key" \
        -H "Content-Type: application/json" \
        -d "$payload") \
        || err "無法連線至 Agenvoy (${AGENVOY_API})，請確認服務已啟動"
    echo "$resp" | python3 -c "import sys,json; d=json.load(sys.stdin); sys.exit(0 if d.get('ok') else 1)" \
        || err "儲存 ${key} 失敗：${resp}"
}
store_key "agenvoy.threads.access_token" "${LONG_TOKEN}"
store_key "agenvoy.threads.app_secret"   "${APP_SECRET}"
store_key "agenvoy.threads.user_id"      "${USER_ID}"
ok "憑證已儲存至 Agenvoy Keychain"

# ── Done ─────────────────────────────────────────────────────────────────────
echo ""
echo "  ════════════════════════════════════════"
ok "Threads 工具安裝完成！"
echo ""
echo "     帳號：@${USERNAME:-$USER_ID}"
echo "     Token 到期：約 ${DAYS} 天後"
echo ""
warn "到期前請執行 threads-refresh-token 工具續期"
echo "  ════════════════════════════════════════"
echo ""
