#!/usr/bin/env bash
# generated by claude sonnet 4.6
set -euo pipefail

# ─────────────────────────────────────────────
#  Threads API one-time installation & setup
# ─────────────────────────────────────────────
GRAPH="https://graph.threads.net"
SERVICE="agenvoy.threads"
INSTALL_DIR="$HOME/.config/agenvoy/script_tools"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)/extensions/scripts"
OS="$(uname -s)"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
ok()   { echo -e "  ${GREEN}✓${NC} $*"; }
warn() { echo -e "  ${YELLOW}!${NC} $*"; }
err()  { echo -e "  ${RED}✗${NC} $*"; exit 1; }

urlencode() {
    python3 -c "import urllib.parse, sys; print(urllib.parse.quote(sys.argv[1]))" "$1"
}

json_get() {
    # json_get <json_string> <key>
    echo "$1" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('$2',''))"
}

json_nested_get() {
    # json_nested_get <json_string> <key1> <key2>
    echo "$1" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('$2',{}).get('$3',''))"
}

install_keyring() {
    if [ "$OS" = "Darwin" ]; then
        python3 -m pip install keyring --quiet --user --break-system-packages
    elif command -v apt-get &>/dev/null; then
        sudo apt-get install -y python3-keyring
    elif command -v dnf &>/dev/null; then
        sudo dnf install -y python3-keyring
    elif command -v pacman &>/dev/null; then
        sudo pacman -S --noconfirm python-keyring
    else
        python3 -m pip install keyring --quiet --user --break-system-packages
    fi
}

# ── Step 1: Install keyring ──────────────────────────────────────────────────
echo ""
echo "  ┌─ Step 1: 安裝 Python 依賴"
if python3 -c "import keyring" &>/dev/null; then
    ok "keyring 已安裝"
else
    warn "keyring 未安裝，安裝中..."
    install_keyring && ok "keyring 安裝完成" || err "keyring 安裝失敗"
fi

# ── Step 2: Install script tools ────────────────────────────────────────────
echo ""
echo "  ┌─ Step 2: 安裝 Threads 工具到 $INSTALL_DIR"
mkdir -p "$INSTALL_DIR"
count=0
for dir in "$SCRIPT_DIR"/threads*/; do
    [ -d "$dir" ] || continue
    name=$(basename "$dir")
    cp -r "$dir" "$INSTALL_DIR/$name"
    ok "$name"
    count=$((count + 1))
done
[ "$count" -gt 0 ] || err "找不到 extensions/scripts/threads* 目錄，請確認從專案根目錄執行此腳本"

# ── Step 3: Collect app credentials ─────────────────────────────────────────
echo ""
echo "  ┌─ Step 3: Threads 設定"
echo "  │  請至 https://developers.facebook.com/apps 準備以下資訊："
echo "  │  App ID 與 App Secret 可在應用程式設定頁面找到"
echo "  │  Short-lived token 請至 Graph API Explorer 產生："
echo "  │  https://developers.facebook.com/tools/explorer"
echo "  │"
read -rp "  │  App ID: " APP_ID
read -rsp "  │  App Secret: " APP_SECRET
echo ""
read -rsp "  │  Short-lived Token (from Graph API Explorer): " SHORT_TOKEN
echo ""

# ── Request 1: short-lived → long-lived token ────────────────────────────────
echo ""
echo "  ┌─ [1/3] 換取 Long-Lived Token..."
R2=$(curl -sf "${GRAPH}/access_token?grant_type=th_exchange_token&client_id=$(urlencode "$APP_ID")&client_secret=$(urlencode "$APP_SECRET")&access_token=$(urlencode "$SHORT_TOKEN")") \
    || err "請求失敗"

LONG_TOKEN=$(json_get "$R2" "access_token")
EXPIRES_IN=$(json_get "$R2" "expires_in")
[ -n "$LONG_TOKEN" ] || err "$(json_nested_get "$R2" "error" "message")"
DAYS=$(( EXPIRES_IN / 86400 ))
ok "Long-lived token 取得成功（有效約 ${DAYS} 天）"

# ── Request 2: get user_id ───────────────────────────────────────────────────
echo ""
echo "  ┌─ [2/3] 取得 User ID..."
R3=$(curl -sf "${GRAPH}/me?access_token=$(urlencode "$LONG_TOKEN")") || err "請求失敗"

USER_ID=$(json_get "$R3" "id")
USERNAME=$(json_get "$R3" "username")
[ -n "$USER_ID" ] || err "無法取得 User ID：$R3"
ok "User ID: ${USER_ID}$( [ -n "$USERNAME" ] && echo " (@${USERNAME})" || true )"

# ── Request 3: save to keychain ─────────────────────────────────────────────
echo ""
echo "  ┌─ [3/3] 儲存憑證至 Keychain..."
python3 - <<PYEOF
import keyring, sys
try:
    keyring.set_password("${SERVICE}", "access_token", """${LONG_TOKEN}""")
    keyring.set_password("${SERVICE}", "app_secret",   """${APP_SECRET}""")
    keyring.set_password("${SERVICE}", "user_id",      """${USER_ID}""")
except Exception as e:
    print(f"  Keychain 寫入失敗: {e}")
    sys.exit(1)
PYEOF
ok "憑證已安全儲存至系統 Keychain"

# ── Done ─────────────────────────────────────────────────────────────────────
echo ""
echo "  ════════════════════════════════════════"
ok "Threads 工具安裝完成！"
echo ""
echo "     帳號：@${USERNAME:-$USER_ID}"
echo "     Token 到期：約 ${DAYS} 天後"
echo ""
warn "到期前請執行 threads-refresh-token 工具續期"
echo "  ════════════════════════════════════════"
echo ""
