#!/usr/bin/env python3
# generated by claude sonnet 4.6
import json
import os
import re
import subprocess
import sys
import unicodedata


def sanitize_filename(name: str) -> str:
    # Normalize Unicode to NFC first
    name = unicodedata.normalize("NFC", name)
    base, ext = os.path.splitext(name)
    # Keep only ASCII alphanumerics, spaces, hyphens, dots
    safe = re.sub(r"[^\w\-. ]", "_", base, flags=re.ASCII)
    safe = re.sub(r"_+", "_", safe).strip("_")
    return (safe or "file") + ext


def main():
    input_data = sys.stdin.read()
    try:
        params = json.loads(input_data) if input_data.strip() else {}
    except json.JSONDecodeError:
        print(json.dumps({"error": "Invalid JSON input"}))
        return

    url = params.get("url")
    output_template = params.get("output_template", "%(title)s.%(ext)s")
    format_str = params.get("format", "bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio/best")
    download_path = params.get("path", os.path.expanduser("~/Downloads"))
    no_playlist = params.get("no_playlist", True)

    if not url:
        print(json.dumps({"error": "Missing required parameter: url"}))
        return

    os.makedirs(download_path, exist_ok=True)

    cmd = [
        sys.executable,
        "-m",
        "yt_dlp",
        "-f",
        format_str,
        "--merge-output-format",
        "mp4",
        "-o",
        os.path.join(download_path, output_template),
    ]
    if no_playlist:
        cmd.append("--no-playlist")
    cmd.append(url)

    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
        if result.returncode == 0:
            # Collect destination files: direct download and post-processed (merge/extract)
            dest_pattern = re.compile(
                r'(?:\[download\] Destination:\s*|\[(?:Merger|ExtractAudio|VideoConvertor)\] (?:Merging formats into|Destination:) ")(.+?)(?:")?$'
            )
            raw_files = []
            seen = set()
            for line in result.stdout.splitlines():
                m = dest_pattern.search(line)
                if m:
                    f = m.group(1).strip().strip('"')
                    if f not in seen:
                        seen.add(f)
                        raw_files.append(f)

            downloaded_files = []
            for f in raw_files:
                safe_name = sanitize_filename(os.path.basename(f))
                safe_path = os.path.join(os.path.dirname(f), safe_name)
                if f != safe_path and os.path.exists(f):
                    os.rename(f, safe_path)
                downloaded_files.append(safe_path)

            print(
                json.dumps(
                    {
                        "success": True,
                        "message": "Download completed successfully",
                        "files": downloaded_files,
                        "path": download_path,
                    }
                )
            )
        else:
            stderr = result.stderr.strip()
            print(
                json.dumps(
                    {
                        "success": False,
                        "error": (stderr[:500] + "...")
                        if len(stderr) > 500
                        else (stderr or "Download failed"),
                        "stdout": result.stdout.strip()[:200],
                    }
                )
            )
    except subprocess.TimeoutExpired:
        print(
            json.dumps(
                {"success": False, "error": "Download timed out after 5 minutes"}
            )
        )
    except Exception as e:
        print(json.dumps({"success": False, "error": str(e)}))


if __name__ == "__main__":
    main()
