// Script tools receive JSON input via stdin (tool parameters object).
// Output the result to stdout (JSON preferred).
// generated by claude sonnet 4.6

const chunks = [];
process.stdin.on("data", (d) => chunks.push(d));
process.stdin.on("end", () => {
  const input = JSON.parse(Buffer.concat(chunks).toString() || "{}");
  const name = (input.name || "").trim() || "World";
  console.log(JSON.stringify({ message: `Hello, ${name}!` }));
});
