// generated by claude sonnet 4.6
const { execFile } = require("child_process");
const chunks = [];

process.stdin.on("data", (d) => chunks.push(d));
process.stdin.on("end", () => {
  let params;
  try {
    params = JSON.parse(Buffer.concat(chunks).toString() || "{}");
  } catch {
    process.stdout.write(JSON.stringify({ error: "Invalid JSON input" }));
    return;
  }

  const { url, list_formats = false } = params;
  if (!url) {
    process.stdout.write(JSON.stringify({ error: "Missing required parameter: url" }));
    return;
  }

  const python = process.execPath.replace(/node$/, "python3").includes("python3") ? process.execPath : "python3";

  // --dump-json: emit full metadata JSON without downloading
  const args = ["-m", "yt_dlp", "--dump-json", "--no-playlist", url];

  execFile(python, args, { timeout: 30000 }, (err, stdout, stderr) => {
    if (err) {
      const msg = (stderr || err.message || "").slice(0, 400);
      process.stdout.write(JSON.stringify({ error: msg || "yt-dlp failed" }));
      return;
    }

    let meta;
    try {
      meta = JSON.parse(stdout.trim());
    } catch {
      process.stdout.write(JSON.stringify({ error: "Failed to parse yt-dlp output" }));
      return;
    }

    // Build concise format list
    const formats = (meta.formats || []).map((f) => ({
      id: f.format_id,
      ext: f.ext,
      resolution: f.resolution || (f.width && f.height ? `${f.width}x${f.height}` : null),
      fps: f.fps || null,
      vcodec: f.vcodec !== "none" ? f.vcodec : null,
      acodec: f.acodec !== "none" ? f.acodec : null,
      filesize: f.filesize || f.filesize_approx || null,
      note: f.format_note || null,
    }));

    // Separate video-only, audio-only, combined
    const videoFormats = formats.filter((f) => f.vcodec && !f.acodec);
    const audioFormats = formats.filter((f) => f.acodec && !f.vcodec);
    const combinedFormats = formats.filter((f) => f.vcodec && f.acodec);

    const result = {
      title: meta.title,
      channel: meta.uploader || meta.channel,
      duration_sec: meta.duration,
      duration_str: meta.duration_string,
      view_count: meta.view_count,
      upload_date: meta.upload_date,
      thumbnail: meta.thumbnail,
      webpage_url: meta.webpage_url,
      extractor: meta.extractor,
    };

    if (list_formats) {
      result.formats = {
        video_only: videoFormats,
        audio_only: audioFormats,
        combined: combinedFormats,
      };
      // Recommended format strings
      const best1080 = videoFormats.find((f) => f.resolution && f.resolution.startsWith("1920"));
      const best720 = videoFormats.find((f) => f.resolution && f.resolution.startsWith("1280"));
      result.suggested_formats = {
        best: "bestvideo+bestaudio/best",
        "1080p": best1080 ? `${best1080.id}+bestaudio/best` : "bestvideo[height<=1080]+bestaudio/best",
        "720p": best720 ? `${best720.id}+bestaudio/best` : "bestvideo[height<=720]+bestaudio/best",
        audio_only: "bestaudio[ext=m4a]/bestaudio",
      };
    }

    process.stdout.write(JSON.stringify(result));
  });
});
