// Generated by Claude Code

package mcp

import (
	"encoding/json"
	"testing"
)

func TestExtractText_SingleText(t *testing.T) {
	raw := json.RawMessage(`{"content":[{"type":"text","text":"hello world"}]}`)
	got, err := extractText(raw)
	if err != nil {
		t.Fatalf("extractText: %v", err)
	}
	if got != "hello world" {
		t.Errorf("got %q, want %q", got, "hello world")
	}
}

func TestExtractText_MultipleText(t *testing.T) {
	raw := json.RawMessage(`{"content":[{"type":"text","text":"line1"},{"type":"text","text":"line2"}]}`)
	got, err := extractText(raw)
	if err != nil {
		t.Fatalf("extractText: %v", err)
	}
	if got != "line1\nline2" {
		t.Errorf("got %q, want %q", got, "line1\nline2")
	}
}

func TestExtractText_Error(t *testing.T) {
	raw := json.RawMessage(`{"content":[{"type":"text","text":"something went wrong"}],"isError":true}`)
	_, err := extractText(raw)
	if err == nil {
		t.Fatal("expected error")
	}
	if err.Error() != "tool error: something went wrong" {
		t.Errorf("err = %q", err)
	}
}

func TestExtractText_ErrorNoContent(t *testing.T) {
	raw := json.RawMessage(`{"content":[],"isError":true}`)
	_, err := extractText(raw)
	if err == nil {
		t.Fatal("expected error")
	}
	if err.Error() != "tool error" {
		t.Errorf("err = %q", err)
	}
}

func TestExtractText_Empty(t *testing.T) {
	got, err := extractText(nil)
	if err != nil {
		t.Fatalf("extractText nil: %v", err)
	}
	if got != "" {
		t.Errorf("got %q for nil input", got)
	}

	got, err = extractText(json.RawMessage(""))
	if err != nil {
		t.Fatalf("extractText empty: %v", err)
	}
	if got != "" {
		t.Errorf("got %q for empty input", got)
	}
}

func TestExtractText_NonTextContent(t *testing.T) {
	raw := json.RawMessage(`{"content":[{"type":"image","text":""}]}`)
	got, err := extractText(raw)
	if err != nil {
		t.Fatalf("extractText: %v", err)
	}
	if got == "" {
		t.Log("empty result for non-text content (fallback to raw)")
	}
}

func TestExtractText_UnparseableJSON(t *testing.T) {
	raw := json.RawMessage(`plain text result`)
	got, err := extractText(raw)
	if err != nil {
		t.Fatalf("extractText: %v", err)
	}
	if got != "plain text result" {
		t.Errorf("got %q, want raw fallback", got)
	}
}

func TestExtractText_NoTextFields(t *testing.T) {
	raw := json.RawMessage(`{"content":[]}`)
	got, err := extractText(raw)
	if err != nil {
		t.Fatalf("extractText: %v", err)
	}
	if got != `{"content":[]}` {
		t.Errorf("got %q, want raw fallback for empty content array", got)
	}
}
