// Generated by Claude Code

package mcp

import (
	"os"
	"testing"
)

func TestServerConfig_IsHTTP(t *testing.T) {
	tests := []struct {
		cfg  ServerConfig
		want bool
	}{
		{ServerConfig{URL: "https://mcp.example.com"}, true},
		{ServerConfig{URL: "  "}, false},
		{ServerConfig{URL: ""}, false},
		{ServerConfig{Command: "npx"}, false},
	}
	for _, tt := range tests {
		if got := tt.cfg.IsHTTP(); got != tt.want {
			t.Errorf("IsHTTP(%+v) = %v, want %v", tt.cfg, got, tt.want)
		}
	}
}

func TestServerConfig_IsStdio(t *testing.T) {
	tests := []struct {
		cfg  ServerConfig
		want bool
	}{
		{ServerConfig{Command: "npx"}, true},
		{ServerConfig{Command: "  "}, false},
		{ServerConfig{Command: ""}, false},
		{ServerConfig{URL: "https://x.com"}, false},
	}
	for _, tt := range tests {
		if got := tt.cfg.IsStdio(); got != tt.want {
			t.Errorf("IsStdio(%+v) = %v, want %v", tt.cfg, got, tt.want)
		}
	}
}

func TestServerConfig_Expand(t *testing.T) {
	os.Setenv("TEST_MCP_TOKEN", "secret123")
	defer os.Unsetenv("TEST_MCP_TOKEN")

	cfg := ServerConfig{
		Command: "npx",
		Args:    []string{"--token", "$TEST_MCP_TOKEN"},
		Env:     map[string]string{"API_KEY": "$TEST_MCP_TOKEN"},
		Headers: map[string]string{
			"Authorization": "Bearer $TEST_MCP_TOKEN",
			"X-Token":       "$TEST_MCP_TOKEN",
		},
	}

	expanded := cfg.Expand()

	if expanded.Command != "npx" {
		t.Errorf("command = %q", expanded.Command)
	}
	if expanded.Args[1] != "secret123" {
		t.Errorf("args[1] = %q, want secret123", expanded.Args[1])
	}
	if expanded.Env["API_KEY"] != "secret123" {
		t.Errorf("env API_KEY = %q", expanded.Env["API_KEY"])
	}
	if expanded.Headers["Authorization"] != "Bearer secret123" {
		t.Errorf("headers Authorization = %q", expanded.Headers["Authorization"])
	}
	if expanded.Headers["X-Token"] != "secret123" {
		t.Errorf("headers X-Token = %q", expanded.Headers["X-Token"])
	}
}

func TestServerConfig_Expand_NormalizesBearerAuthorization(t *testing.T) {
	os.Setenv("TEST_MCP_TOKEN", "secret123")
	defer os.Unsetenv("TEST_MCP_TOKEN")

	cfg := ServerConfig{
		Headers: map[string]string{"Authorization": "$TEST_MCP_TOKEN"},
	}

	expanded := cfg.Expand()
	if expanded.Headers["Authorization"] != "Bearer secret123" {
		t.Errorf("headers Authorization = %q", expanded.Headers["Authorization"])
	}
}

func TestServerConfig_Expand_KeepsExplicitAuthorizationScheme(t *testing.T) {
	tests := []string{
		"Bearer secret123",
		"Basic c2VjcmV0",
		"token ghp_secret123",
	}

	for _, auth := range tests {
		cfg := ServerConfig{
			Headers: map[string]string{"Authorization": auth},
		}

		expanded := cfg.Expand()
		if expanded.Headers["Authorization"] != auth {
			t.Errorf("headers Authorization = %q, want %q", expanded.Headers["Authorization"], auth)
		}
	}
}

func TestServerConfig_Expand_Empty(t *testing.T) {
	cfg := ServerConfig{Command: "echo"}
	expanded := cfg.Expand()
	if expanded.Args != nil {
		t.Errorf("args should be nil, got %v", expanded.Args)
	}
	if expanded.Env != nil {
		t.Errorf("env should be nil, got %v", expanded.Env)
	}
	if expanded.Headers != nil {
		t.Errorf("headers should be nil, got %v", expanded.Headers)
	}
}

func TestLoad_NoFile(t *testing.T) {
	cfg, err := Load()
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if cfg.Servers == nil {
		t.Error("Servers should be initialized")
	}
}
