// Generated by Claude Code

package mcp

import (
	"os"
	"testing"
)

func TestServerConfig_IsHTTP(t *testing.T) {
	tests := []struct {
		cfg  ServerConfig
		want bool
	}{
		{ServerConfig{URL: "https://mcp.example.com"}, true},
		{ServerConfig{URL: "  "}, false},
		{ServerConfig{URL: ""}, false},
		{ServerConfig{Command: "npx"}, false},
	}
	for _, tt := range tests {
		if got := tt.cfg.IsHTTP(); got != tt.want {
			t.Errorf("IsHTTP(%+v) = %v, want %v", tt.cfg, got, tt.want)
		}
	}
}

func TestServerConfig_IsStdio(t *testing.T) {
	tests := []struct {
		cfg  ServerConfig
		want bool
	}{
		{ServerConfig{Command: "npx"}, true},
		{ServerConfig{Command: "  "}, false},
		{ServerConfig{Command: ""}, false},
		{ServerConfig{URL: "https://x.com"}, false},
	}
	for _, tt := range tests {
		if got := tt.cfg.IsStdio(); got != tt.want {
			t.Errorf("IsStdio(%+v) = %v, want %v", tt.cfg, got, tt.want)
		}
	}
}

func TestServerConfig_Expand(t *testing.T) {
	os.Setenv("TEST_MCP_TOKEN", "secret123")
	defer os.Unsetenv("TEST_MCP_TOKEN")

	cfg := ServerConfig{
		Command: "npx",
		Args:    []string{"--token", "$TEST_MCP_TOKEN"},
		Env:     map[string]string{"API_KEY": "$TEST_MCP_TOKEN"},
		Headers: map[string]string{"Authorization": "Bearer $TEST_MCP_TOKEN"},
	}

	expanded := cfg.Expand()

	if expanded.Command != "npx" {
		t.Errorf("command = %q", expanded.Command)
	}
	if expanded.Args[1] != "secret123" {
		t.Errorf("args[1] = %q, want secret123", expanded.Args[1])
	}
	if expanded.Env["API_KEY"] != "secret123" {
		t.Errorf("env API_KEY = %q", expanded.Env["API_KEY"])
	}
	if expanded.Headers["Authorization"] != "Bearer secret123" {
		t.Errorf("headers Authorization = %q", expanded.Headers["Authorization"])
	}
}

func TestServerConfig_Expand_Empty(t *testing.T) {
	cfg := ServerConfig{Command: "echo"}
	expanded := cfg.Expand()
	if expanded.Args != nil {
		t.Errorf("args should be nil, got %v", expanded.Args)
	}
	if expanded.Env != nil {
		t.Errorf("env should be nil, got %v", expanded.Env)
	}
	if expanded.Headers != nil {
		t.Errorf("headers should be nil, got %v", expanded.Headers)
	}
}

func TestLoad_MissingFile(t *testing.T) {
	cfg, err := Load("/nonexistent/mcp.json")
	if err != nil {
		t.Fatalf("Load missing: %v", err)
	}
	if cfg.Servers == nil {
		t.Error("Servers should be initialized")
	}
	if len(cfg.Servers) != 0 {
		t.Errorf("Servers len = %d, want 0", len(cfg.Servers))
	}
}

func TestLoad_EmptyPath(t *testing.T) {
	cfg, err := Load("")
	if err != nil {
		t.Fatalf("Load empty: %v", err)
	}
	if cfg.Servers == nil {
		t.Error("Servers should be initialized")
	}
}
