// Generated by Claude Code

package mcp

import (
	"encoding/json"
	"strings"
	"testing"
)

func TestParse_Success(t *testing.T) {
	raw := []byte(`{"jsonrpc":"2.0","id":1,"result":{"tools":[]}}`)
	result, err := parse(raw, 1)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if result == nil {
		t.Fatal("result is nil")
	}

	var data map[string]any
	json.Unmarshal(result, &data)
	if _, ok := data["tools"]; !ok {
		t.Error("expected tools in result")
	}
}

func TestParse_RPCError(t *testing.T) {
	raw := []byte(`{"jsonrpc":"2.0","id":1,"error":{"code":-32600,"message":"Invalid Request"}}`)
	_, err := parse(raw, 1)
	if err == nil {
		t.Fatal("expected error")
	}
	if !strings.Contains(err.Error(), "Invalid Request") {
		t.Errorf("err = %v", err)
	}
}

func TestParse_IDMismatch(t *testing.T) {
	raw := []byte(`{"jsonrpc":"2.0","id":99,"result":{}}`)
	_, err := parse(raw, 1)
	if err == nil {
		t.Fatal("expected error for ID mismatch")
	}
	if !strings.Contains(err.Error(), "mismatch") {
		t.Errorf("err = %v", err)
	}
}

func TestParse_NoID(t *testing.T) {
	raw := []byte(`{"jsonrpc":"2.0","result":{"data":"ok"}}`)
	result, err := parse(raw, 1)
	if err != nil {
		t.Fatalf("parse no-id: %v", err)
	}
	if result == nil {
		t.Error("result should not be nil")
	}
}

func TestParse_InvalidJSON(t *testing.T) {
	_, err := parse([]byte("not json"), 1)
	if err == nil {
		t.Error("expected error for invalid JSON")
	}
}

func TestParseSSE_Basic(t *testing.T) {
	sse := "data: {\"jsonrpc\":\"2.0\",\"id\":1,\"result\":{\"key\":\"value\"}}\n\n"
	result, err := parseSSE(strings.NewReader(sse), 1)
	if err != nil {
		t.Fatalf("parseSSE: %v", err)
	}

	var data map[string]any
	json.Unmarshal(result, &data)
	if data["key"] != "value" {
		t.Errorf("result = %v", data)
	}
}

func TestParseSSE_MultiLine(t *testing.T) {
	sse := "data: {\"jsonrpc\":\"2.0\",\n" +
		"data: \"id\":1,\n" +
		"data: \"result\":{\"ok\":true}}\n\n"
	result, err := parseSSE(strings.NewReader(sse), 1)
	if err != nil {
		t.Fatalf("parseSSE: %v", err)
	}

	var data map[string]any
	json.Unmarshal(result, &data)
	if data["ok"] != true {
		t.Errorf("result = %v", data)
	}
}

func TestParseSSE_EmptyStream(t *testing.T) {
	_, err := parseSSE(strings.NewReader(""), 1)
	if err == nil {
		t.Error("expected error for empty SSE stream")
	}
	if !strings.Contains(err.Error(), "ended without") {
		t.Errorf("err = %v", err)
	}
}

func TestParseSSE_SkipsNonDataLines(t *testing.T) {
	sse := "event: message\nid: 42\ndata: {\"jsonrpc\":\"2.0\",\"id\":1,\"result\":{}}\n\n"
	result, err := parseSSE(strings.NewReader(sse), 1)
	if err != nil {
		t.Fatalf("parseSSE: %v", err)
	}
	if result == nil {
		t.Error("expected non-nil result")
	}
}

func TestParseSSE_RPCError(t *testing.T) {
	sse := "data: {\"jsonrpc\":\"2.0\",\"id\":1,\"error\":{\"code\":-1,\"message\":\"fail\"}}\n\n"
	_, err := parseSSE(strings.NewReader(sse), 1)
	if err == nil {
		t.Error("expected error")
	}
}
