#!/usr/bin/env python3
# Script tools receive JSON input via stdin (tool parameters object).
# Output the result to stdout (JSON preferred).
# generated by claude sonnet 4.6

import json
import sys

raw = sys.stdin.read()
params = json.loads(raw or "{}")
name = (params.get("name") or "").strip() or "World"
print(json.dumps({"message": f"Hello, {name}!"}))
