// Generated by Claude Code

package apiAdapter

import (
	"encoding/json"
	"os"
	"path/filepath"
	"slices"
	"testing"
	"testing/fstest"
)

func TestCheck_Valid(t *testing.T) {
	tr := New("api_")
	doc := &Document{
		Name:        "test_api",
		Description: "A test API",
	}
	doc.Endpoint.URL = "https://api.example.com"
	doc.Endpoint.Method = "get"

	if err := tr.check(doc); err != nil {
		t.Fatalf("check: %v", err)
	}
	if doc.Endpoint.Method != "GET" {
		t.Errorf("method not uppercased: %s", doc.Endpoint.Method)
	}
	if doc.Endpoint.ContentType != "json" {
		t.Errorf("content_type default = %s, want json", doc.Endpoint.ContentType)
	}
}

func TestCheck_MissingFields(t *testing.T) {
	tr := New("api_")
	tests := []struct {
		name string
		doc  Document
	}{
		{"no name", Document{Description: "d"}},
		{"no description", Document{Name: "n"}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			doc := tt.doc
			doc.Endpoint.URL = "https://x.com"
			doc.Endpoint.Method = "GET"
			if err := tr.check(&doc); err == nil {
				t.Error("expected error")
			}
		})
	}
}

func TestCheck_MissingEndpoint(t *testing.T) {
	tr := New("api_")
	doc := &Document{Name: "n", Description: "d"}

	doc.Endpoint.Method = "GET"
	if err := tr.check(doc); err == nil {
		t.Error("expected error for missing URL")
	}

	doc.Endpoint.URL = "https://x.com"
	doc.Endpoint.Method = ""
	if err := tr.check(doc); err == nil {
		t.Error("expected error for missing method")
	}
}

func TestCheck_UnsupportedMethod(t *testing.T) {
	tr := New("api_")
	doc := &Document{Name: "n", Description: "d"}
	doc.Endpoint.URL = "https://x.com"
	doc.Endpoint.Method = "OPTIONS"

	if err := tr.check(doc); err == nil {
		t.Error("expected error for OPTIONS method")
	}
}

func TestLoad_Directory(t *testing.T) {
	dir := t.TempDir()

	doc := map[string]any{
		"name":        "weather",
		"description": "Get weather",
		"endpoint":    map[string]any{"url": "https://api.weather.com", "method": "GET"},
	}
	raw, _ := json.Marshal(doc)
	os.WriteFile(filepath.Join(dir, "weather.json"), raw, 0644)

	os.WriteFile(filepath.Join(dir, "not-json.txt"), []byte("hello"), 0644)

	tr := New("api_")
	if err := tr.Load(dir); err != nil {
		t.Fatalf("Load: %v", err)
	}

	if !tr.IsExist("api_weather") {
		t.Error("expected weather tool to exist")
	}
	if tr.IsExist("api_notexist") {
		t.Error("expected nonexistent tool to not exist")
	}
}

func TestLoad_NonexistentDir(t *testing.T) {
	tr := New("api_")
	if err := tr.Load("/nonexistent/path"); err != nil {
		t.Errorf("Load nonexistent dir should return nil, got: %v", err)
	}
}

func TestLoadBuiltin(t *testing.T) {
	fsys := fstest.MapFS{
		"tools/weather.json": &fstest.MapFile{
			Data: []byte(`{"name":"weather","description":"Weather API","endpoint":{"url":"https://api.weather.com","method":"GET"}}`),
		},
		"tools/skip.txt": &fstest.MapFile{
			Data: []byte("not json"),
		},
	}

	tr := New("api_")
	if err := tr.Builtin(fsys, "tools"); err != nil {
		t.Fatalf("LoadBuiltin: %v", err)
	}

	if !tr.IsExist("api_weather") {
		t.Error("expected weather tool from FS")
	}
}

func TestGetTools(t *testing.T) {
	tr := New("api_")
	tr.apis["test"] = &Document{Name: "test", Description: "d"}

	tools := tr.GetTools()
	if len(tools) != 1 {
		t.Fatalf("len = %d, want 1", len(tools))
	}
	fn := tools[0]["function"].(map[string]any)
	if fn["name"] != "api_test" {
		t.Errorf("name = %v", fn["name"])
	}
}

func TestAlwaysAllowNames(t *testing.T) {
	tr := New("api_")
	tr.apis["a"] = &Document{Name: "a", AlwaysAllow: true}
	tr.apis["b"] = &Document{Name: "b", AlwaysAllow: false}
	tr.apis["c"] = &Document{Name: "c", AlwaysAllow: true}

	names := tr.AlwaysAllowNames()
	if len(names) != 2 {
		t.Fatalf("len = %d, want 2", len(names))
	}
	if !slices.Contains(names, "api_a") || !slices.Contains(names, "api_c") {
		t.Errorf("names = %v", names)
	}
}

func TestConcurrentNames(t *testing.T) {
	tr := New("api_")
	tr.apis["x"] = &Document{Name: "x", Concurrent: true}
	tr.apis["y"] = &Document{Name: "y"}
	tr.apis["z"] = &Document{Name: "z", Concurrent: true}

	names := tr.ConcurrentNames()
	if len(names) != 2 {
		t.Fatalf("len = %d, want 2", len(names))
	}
	if !slices.Contains(names, "api_x") || !slices.Contains(names, "api_z") {
		t.Errorf("names = %v", names)
	}
}
