// Generated by Claude Code

package apiAdapter

import (
	"context"
	"testing"
)

func TestCheckRequireds(t *testing.T) {
	tr := New("api_")
	doc := &Document{}
	doc.Parameters = map[string]struct {
		Type        string `json:"type"`
		Description string `json:"description"`
		Required    bool   `json:"required"`
		Default     any    `json:"default,omitempty"`
		Enum        []any  `json:"enum,omitempty"`
	}{
		"city":   {Type: "string", Required: true},
		"unit":   {Type: "string", Required: false, Default: "celsius"},
		"format": {Type: "string", Required: false},
	}

	params := map[string]any{"city": "Tokyo"}
	if err := tr.checkParams(doc, params); err != nil {
		t.Fatalf("checkRequireds: %v", err)
	}
	if params["unit"] != "celsius" {
		t.Errorf("unit default = %v, want celsius", params["unit"])
	}
	if _, ok := params["format"]; ok {
		t.Error("format should not be set (no default)")
	}
}

func TestCheckRequireds_MissingRequired(t *testing.T) {
	tr := New("api_")
	doc := &Document{}
	doc.Parameters = map[string]struct {
		Type        string `json:"type"`
		Description string `json:"description"`
		Required    bool   `json:"required"`
		Default     any    `json:"default,omitempty"`
		Enum        []any  `json:"enum,omitempty"`
	}{
		"city": {Type: "string", Required: true},
	}

	if err := tr.checkParams(doc, map[string]any{}); err == nil {
		t.Error("expected error for missing required param")
	}
}

func TestExecute_NotFound(t *testing.T) {
	tr := New("api_")
	_, err := tr.Execute(context.Background(), "api_nonexistent", map[string]any{})
	if err == nil {
		t.Error("expected error for nonexistent tool")
	}
}
