// Generated by Claude Code

package apiAdapter

import (
	"io"
	"net/http"
	"strings"
	"testing"
)

func TestReplaceParams(t *testing.T) {
	tests := []struct {
		name     string
		url      string
		params   map[string]any
		wantURL  string
		wantLeft map[string]any
	}{
		{
			name:     "single placeholder",
			url:      "https://api.example.com/users/{id}",
			params:   map[string]any{"id": 42, "name": "test"},
			wantURL:  "https://api.example.com/users/42",
			wantLeft: map[string]any{"name": "test"},
		},
		{
			name:     "multiple placeholders",
			url:      "https://api.example.com/{org}/{repo}",
			params:   map[string]any{"org": "foo", "repo": "bar"},
			wantURL:  "https://api.example.com/foo/bar",
			wantLeft: map[string]any{},
		},
		{
			name:     "url encode special chars",
			url:      "https://api.example.com/search/{q}",
			params:   map[string]any{"q": "hello world"},
			wantURL:  "https://api.example.com/search/hello%20world",
			wantLeft: map[string]any{},
		},
		{
			name:     "no placeholders",
			url:      "https://api.example.com/data",
			params:   map[string]any{"key": "val"},
			wantURL:  "https://api.example.com/data",
			wantLeft: map[string]any{"key": "val"},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			doc := &APIDocumentData{}
			doc.Endpoint.URL = tt.url
			params := make(map[string]any)
			for k, v := range tt.params {
				params[k] = v
			}
			got := replaceParams(doc, params)
			if got != tt.wantURL {
				t.Errorf("url = %q, want %q", got, tt.wantURL)
			}
			if len(params) != len(tt.wantLeft) {
				t.Errorf("remaining params = %v, want %v", params, tt.wantLeft)
			}
		})
	}
}

func TestTrimUnused(t *testing.T) {
	tests := []struct {
		input string
		want  string
	}{
		{"https://api.com/data", "https://api.com/data"},
		{"https://api.com/{unused}/data", "https://api.com/data"},
		{"https://api.com/a/{b}/{c}", "https://api.com/a"},
		{"https://api.com/{a}", "https://api.com"},
	}

	for _, tt := range tests {
		t.Run(tt.input, func(t *testing.T) {
			got := trimUnused(tt.input)
			if got != tt.want {
				t.Errorf("trimUnused(%q) = %q, want %q", tt.input, got, tt.want)
			}
		})
	}
}

func TestJSONRequest_GET(t *testing.T) {
	tr := New("api_")
	doc := &APIDocumentData{}
	doc.Endpoint.URL = "https://api.example.com/data"
	doc.Endpoint.Method = "GET"
	doc.Endpoint.Query = map[string]string{"format": "json"}

	req, err := tr.JSONRequest(doc, map[string]any{"q": "test"})
	if err != nil {
		t.Fatalf("JSONRequest: %v", err)
	}
	if req.Method != "GET" {
		t.Errorf("method = %s", req.Method)
	}
	if req.Body != nil {
		t.Error("GET request should have nil body")
	}
	q := req.URL.Query()
	if q.Get("format") != "json" {
		t.Errorf("query format = %q", q.Get("format"))
	}
	if q.Get("q") != "test" {
		t.Errorf("query q = %q", q.Get("q"))
	}
}

func TestJSONRequest_POST(t *testing.T) {
	tr := New("api_")
	doc := &APIDocumentData{}
	doc.Endpoint.URL = "https://api.example.com/data"
	doc.Endpoint.Method = "POST"

	req, err := tr.JSONRequest(doc, map[string]any{"key": "value"})
	if err != nil {
		t.Fatalf("JSONRequest: %v", err)
	}
	if req.Method != "POST" {
		t.Errorf("method = %s", req.Method)
	}
	if req.Header.Get("Content-Type") != "application/json" {
		t.Errorf("content-type = %s", req.Header.Get("Content-Type"))
	}
	body, _ := io.ReadAll(req.Body)
	if !strings.Contains(string(body), `"key":"value"`) {
		t.Errorf("body = %s", body)
	}
}

func TestJSONRequest_POST_EmptyParams(t *testing.T) {
	tr := New("api_")
	doc := &APIDocumentData{}
	doc.Endpoint.URL = "https://api.example.com/data"
	doc.Endpoint.Method = "POST"

	req, err := tr.JSONRequest(doc, map[string]any{})
	if err != nil {
		t.Fatalf("JSONRequest: %v", err)
	}
	if req.Body != http.NoBody && req.Body != nil {
		body, _ := io.ReadAll(req.Body)
		if len(body) > 0 {
			t.Errorf("expected no body for empty params, got %s", body)
		}
	}
}

func TestFormDataRequest(t *testing.T) {
	tr := New("api_")
	doc := &APIDocumentData{}
	doc.Endpoint.URL = "https://api.example.com/submit"
	doc.Endpoint.Method = "POST"

	req, err := tr.FormDataRequest(doc, map[string]any{"field": "value", "num": 42})
	if err != nil {
		t.Fatalf("FormDataRequest: %v", err)
	}
	if req.Header.Get("Content-Type") != "application/x-www-form-urlencoded" {
		t.Errorf("content-type = %s", req.Header.Get("Content-Type"))
	}
	body, _ := io.ReadAll(req.Body)
	s := string(body)
	if !strings.Contains(s, "field=value") {
		t.Errorf("body missing field=value: %s", s)
	}
}
