// Generated by Claude Code

package apiAdapter

import (
	"testing"
)

func TestReplaceParams(t *testing.T) {
	tests := []struct {
		name     string
		url      string
		params   map[string]any
		wantURL  string
		wantLeft map[string]any
	}{
		{
			name:     "single placeholder",
			url:      "https://api.example.com/users/{id}",
			params:   map[string]any{"id": 42, "name": "test"},
			wantURL:  "https://api.example.com/users/42",
			wantLeft: map[string]any{"name": "test"},
		},
		{
			name:     "multiple placeholders",
			url:      "https://api.example.com/{org}/{repo}",
			params:   map[string]any{"org": "foo", "repo": "bar"},
			wantURL:  "https://api.example.com/foo/bar",
			wantLeft: map[string]any{},
		},
		{
			name:     "url encode special chars",
			url:      "https://api.example.com/search/{q}",
			params:   map[string]any{"q": "hello world"},
			wantURL:  "https://api.example.com/search/hello%20world",
			wantLeft: map[string]any{},
		},
		{
			name:     "no placeholders",
			url:      "https://api.example.com/data",
			params:   map[string]any{"key": "val"},
			wantURL:  "https://api.example.com/data",
			wantLeft: map[string]any{"key": "val"},
		},
		{
			name:     "unused placeholder trimmed",
			url:      "https://api.com/{unused}/data",
			params:   map[string]any{},
			wantURL:  "https://api.com/data",
			wantLeft: map[string]any{},
		},
		{
			name:     "multiple unused placeholders trimmed",
			url:      "https://api.com/a/{b}/{c}",
			params:   map[string]any{},
			wantURL:  "https://api.com/a",
			wantLeft: map[string]any{},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			doc := &Document{}
			doc.Endpoint.URL = tt.url
			params := make(map[string]any)
			for k, v := range tt.params {
				params[k] = v
			}
			got := replaceParams(doc, params)
			if got != tt.wantURL {
				t.Errorf("url = %q, want %q", got, tt.wantURL)
			}
			if len(params) != len(tt.wantLeft) {
				t.Errorf("remaining params = %v, want %v", params, tt.wantLeft)
			}
		})
	}
}
