// Generated by Claude Code

package apiAdapter

import (
	"encoding/json"
	"testing"
)

func TestTranslate_Basic(t *testing.T) {
	doc := &Document{
		Name:        "get_weather",
		Description: "Fetch weather data",
	}
	doc.Parameters = map[string]struct {
		Type        string `json:"type"`
		Description string `json:"description"`
		Required    bool   `json:"required"`
		Default     any    `json:"default,omitempty"`
		Enum        []any  `json:"enum,omitempty"`
	}{
		"city": {Type: "string", Description: "City name", Required: true},
	}

	result := doc.translate("api_")

	if result["type"] != "function" {
		t.Fatalf("type = %v, want function", result["type"])
	}
	fn := result["function"].(map[string]any)
	if fn["name"] != "api_get_weather" {
		t.Errorf("name = %v, want api_get_weather", fn["name"])
	}
	if fn["description"] != "Fetch weather data" {
		t.Errorf("description = %v", fn["description"])
	}

	var params map[string]any
	if err := json.Unmarshal(fn["parameters"].(json.RawMessage), &params); err != nil {
		t.Fatalf("unmarshal parameters: %v", err)
	}
	props := params["properties"].(map[string]any)
	city := props["city"].(map[string]any)
	if city["type"] != "string" {
		t.Errorf("city.type = %v", city["type"])
	}

	required := params["required"].([]any)
	if len(required) != 1 || required[0] != "city" {
		t.Errorf("required = %v, want [city]", required)
	}
}

func TestTranslate_NoRequired(t *testing.T) {
	doc := &Document{
		Name:        "test",
		Description: "desc",
	}
	doc.Parameters = map[string]struct {
		Type        string `json:"type"`
		Description string `json:"description"`
		Required    bool   `json:"required"`
		Default     any    `json:"default,omitempty"`
		Enum        []any  `json:"enum,omitempty"`
	}{
		"opt": {Type: "string", Description: "optional"},
	}

	result := doc.translate("")
	fn := result["function"].(map[string]any)

	var params map[string]any
	if err := json.Unmarshal(fn["parameters"].(json.RawMessage), &params); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	if _, ok := params["required"]; ok {
		t.Error("expected no required field for optional-only params")
	}
}

func TestTranslate_EnumAndDefault(t *testing.T) {
	doc := &Document{
		Name:        "test",
		Description: "desc",
	}
	doc.Parameters = map[string]struct {
		Type        string `json:"type"`
		Description string `json:"description"`
		Required    bool   `json:"required"`
		Default     any    `json:"default,omitempty"`
		Enum        []any  `json:"enum,omitempty"`
	}{
		"unit": {Type: "string", Description: "unit", Enum: []any{"c", "f"}, Default: "c"},
	}

	result := doc.translate("")
	fn := result["function"].(map[string]any)
	var params map[string]any
	json.Unmarshal(fn["parameters"].(json.RawMessage), &params)
	props := params["properties"].(map[string]any)
	unit := props["unit"].(map[string]any)

	if unit["default"] != "c" {
		t.Errorf("default = %v, want c", unit["default"])
	}
	enums := unit["enum"].([]any)
	if len(enums) != 2 {
		t.Errorf("enum len = %d, want 2", len(enums))
	}
}

func TestTranslate_EmptyParams(t *testing.T) {
	doc := &Document{
		Name:        "test",
		Description: "desc",
	}

	result := doc.translate("x_")
	fn := result["function"].(map[string]any)
	if fn["name"] != "x_test" {
		t.Errorf("name = %v", fn["name"])
	}
}
