// Generated by Claude Code

package scriptAdapter

import (
	"encoding/json"
	"os"
	"path/filepath"
	"slices"
	"testing"
)

func TestNew(t *testing.T) {
	tr := New("script_")
	if tr.prefix != "script_" {
		t.Errorf("prefix = %q", tr.prefix)
	}
	if tr.scripts == nil {
		t.Error("scripts map not initialized")
	}
}

func TestIsExist(t *testing.T) {
	tr := New("script_")
	tr.scripts["weather"] = &Script{Doc: ScriptDoc{Name: "weather"}}

	if !tr.IsExist("script_weather") {
		t.Error("expected weather to exist with prefix")
	}
	if !tr.IsExist("weather") {
		t.Error("expected weather to exist without prefix")
	}
	if tr.IsExist("script_nonexistent") {
		t.Error("expected nonexistent to not exist")
	}
}

func TestGetTools(t *testing.T) {
	tr := New("script_")
	tr.scripts["test"] = &Script{
		Doc: ScriptDoc{
			Name:        "test",
			Description: "A test tool",
			Parameters:  json.RawMessage(`{"type":"object","properties":{"q":{"type":"string"}}}`),
		},
	}

	tools := tr.GetTools()
	if len(tools) != 1 {
		t.Fatalf("len = %d, want 1", len(tools))
	}

	fn := tools[0]["function"].(map[string]any)
	if fn["name"] != "script_test" {
		t.Errorf("name = %v", fn["name"])
	}
	if fn["description"] != "A test tool" {
		t.Errorf("description = %v", fn["description"])
	}

	params := fn["parameters"].(json.RawMessage)
	var p map[string]any
	json.Unmarshal(params, &p)
	if p["type"] != "object" {
		t.Errorf("params type = %v", p["type"])
	}
}

func TestGetTools_DefaultParams(t *testing.T) {
	tr := New("script_")
	tr.scripts["empty"] = &Script{
		Doc: ScriptDoc{Name: "empty", Description: "no params"},
	}

	tools := tr.GetTools()
	fn := tools[0]["function"].(map[string]any)
	params := fn["parameters"].(json.RawMessage)

	var p map[string]any
	json.Unmarshal(params, &p)
	if p["type"] != "object" {
		t.Errorf("default params type = %v", p["type"])
	}
}

func TestAlwaysAllowNames(t *testing.T) {
	tr := New("script_")
	tr.scripts["a"] = &Script{Doc: ScriptDoc{Name: "a", AlwaysAllow: true}}
	tr.scripts["b"] = &Script{Doc: ScriptDoc{Name: "b", AlwaysAllow: false}}
	tr.scripts["c"] = &Script{Doc: ScriptDoc{Name: "c", AlwaysAllow: true}}

	names := tr.AlwaysAllowNames()
	if len(names) != 2 {
		t.Fatalf("len = %d, want 2", len(names))
	}
	if !slices.Contains(names, "script_a") || !slices.Contains(names, "script_c") {
		t.Errorf("names = %v", names)
	}
}

func TestConcurrentNames(t *testing.T) {
	tr := New("ext_")
	tr.scripts["x"] = &Script{Doc: ScriptDoc{Name: "x"}}
	tr.scripts["y"] = &Script{Doc: ScriptDoc{Name: "y"}}

	names := tr.ConcurrentNames()
	if len(names) != 2 {
		t.Fatalf("len = %d, want 2", len(names))
	}
	if !slices.Contains(names, "ext_x") || !slices.Contains(names, "ext_y") {
		t.Errorf("names = %v", names)
	}
}

func TestTimeouts(t *testing.T) {
	tr := New("script_")
	tr.scripts["fast"] = &Script{Doc: ScriptDoc{Name: "fast", Timeout: 10}}
	tr.scripts["slow"] = &Script{Doc: ScriptDoc{Name: "slow", Timeout: 600}}
	tr.scripts["default"] = &Script{Doc: ScriptDoc{Name: "default"}}

	timeouts := tr.Timeouts()
	if timeouts["script_fast"] != 10 {
		t.Errorf("fast timeout = %d", timeouts["script_fast"])
	}
	if timeouts["script_slow"] != 600 {
		t.Errorf("slow timeout = %d", timeouts["script_slow"])
	}
	if _, ok := timeouts["script_default"]; ok {
		t.Error("default (0) timeout should not be in map")
	}
}

func TestScan(t *testing.T) {
	root := t.TempDir()

	toolDir := filepath.Join(root, "my_script")
	os.MkdirAll(toolDir, 0755)

	doc := ScriptDoc{Name: "my_script", Description: "Test script"}
	raw, _ := json.Marshal(doc)
	os.WriteFile(filepath.Join(toolDir, "tool.json"), raw, 0644)
	os.WriteFile(filepath.Join(toolDir, "script.js"), []byte("console.log('hello')"), 0644)

	hidden := filepath.Join(root, "_skip")
	os.MkdirAll(hidden, 0755)

	dotHidden := filepath.Join(root, ".hidden")
	os.MkdirAll(dotHidden, 0755)

	tr := New("script_")
	if err := tr.Scan(root); err != nil {
		t.Fatalf("Scan: %v", err)
	}

	if !tr.IsExist("script_my_script") {
		t.Error("expected my_script to exist")
	}
	if len(tr.scripts) != 1 {
		t.Errorf("scripts count = %d, want 1", len(tr.scripts))
	}
}

func TestScan_NonexistentDir(t *testing.T) {
	tr := New("script_")
	if err := tr.Scan("/nonexistent/dir"); err != nil {
		t.Errorf("Scan nonexistent should return nil: %v", err)
	}
}

func TestScan_PythonScript(t *testing.T) {
	root := t.TempDir()
	toolDir := filepath.Join(root, "py_tool")
	os.MkdirAll(toolDir, 0755)

	doc := ScriptDoc{Name: "py_tool", Description: "Python tool"}
	raw, _ := json.Marshal(doc)
	os.WriteFile(filepath.Join(toolDir, "tool.json"), raw, 0644)
	os.WriteFile(filepath.Join(toolDir, "script.py"), []byte("print('hello')"), 0644)

	tr := New("script_")
	if err := tr.Scan(root); err != nil {
		t.Fatalf("Scan: %v", err)
	}

	if !tr.IsExist("script_py_tool") {
		t.Error("expected py_tool to exist")
	}
	if tr.scripts["py_tool"].language != "python" {
		t.Errorf("language = %q, want python", tr.scripts["py_tool"].language)
	}
}

func TestScan_NoScript(t *testing.T) {
	root := t.TempDir()
	toolDir := filepath.Join(root, "no_script")
	os.MkdirAll(toolDir, 0755)

	doc := ScriptDoc{Name: "no_script", Description: "Missing script"}
	raw, _ := json.Marshal(doc)
	os.WriteFile(filepath.Join(toolDir, "tool.json"), raw, 0644)

	tr := New("script_")
	tr.Scan(root)

	if tr.IsExist("script_no_script") {
		t.Error("should not load tool without script file")
	}
}

func TestScan_InvalidName(t *testing.T) {
	root := t.TempDir()
	toolDir := filepath.Join(root, "bad")
	os.MkdirAll(toolDir, 0755)

	doc := ScriptDoc{Name: "../escape", Description: "Bad name"}
	raw, _ := json.Marshal(doc)
	os.WriteFile(filepath.Join(toolDir, "tool.json"), raw, 0644)
	os.WriteFile(filepath.Join(toolDir, "script.js"), []byte("x"), 0644)

	tr := New("script_")
	tr.Scan(root)

	if tr.IsExist("script_../escape") {
		t.Error("should reject path traversal name")
	}
}

func TestScan_EmptyName(t *testing.T) {
	root := t.TempDir()
	toolDir := filepath.Join(root, "empty_name")
	os.MkdirAll(toolDir, 0755)

	doc := ScriptDoc{Description: "No name"}
	raw, _ := json.Marshal(doc)
	os.WriteFile(filepath.Join(toolDir, "tool.json"), raw, 0644)
	os.WriteFile(filepath.Join(toolDir, "script.js"), []byte("x"), 0644)

	tr := New("script_")
	tr.Scan(root)

	if len(tr.scripts) != 0 {
		t.Error("should reject empty name")
	}
}
